### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'device_id'

### ISSUE THREAD

**Issue by pergolafabio** [RogerSelwyn/mqtt_discoverystream_ha#3]
Hi

still on 2022.7.3 , but updated your hacs version to: 0.10.11

now i have a lot of these in my logs? Do i need to fiest update for 2023.8.x ?

```
       ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'device_id'
2023-08-03 15:07:17.741 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/mqtt_discoverystream/__init__.py", line 52, in _state_publisher
    await discovery.async_state_publish(entity_id, new_state, mybase)
  File "/config/custom_components/mqtt_discoverystream/discovery.py", line 102, in async_state_publish
    await self._async_discovery_publish(entity_id, new_state.attributes, mybase)
  File "/config/custom_components/mqtt_discoverystream/discovery.py", line 127, in _async_discovery_publish
    config = self._build_base(entity_id, attributes, mybase)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mqtt_discoverystream/discovery.py", line 191, in _build_base
    if entry.device_id and name:
       ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'device_id'
2023-08-03 15:07:17.743 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/mqtt_discoverystream/__init__.py", line 52, in _state_publisher
    await discovery.async_state_publish(entity_id, new_state, mybase)
  File "/config/custom_components/mqtt_discoverystream/discovery.py", line 102, in async_state_publish
    await self._async_discovery_publish(entity_id, new_state.attributes, mybase)
  File "/config/custom_components/mqtt_discoverystream/discovery.py", line 127, in _async_discovery_publish
    config = self._build_base(entity_id, attributes, mybase)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mqtt_discoverystream/discovery.py", line 191, in _build_base
    if entry.device_id and name:
       ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'device_id'
2023-08-03 15:07:17.744 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/mqtt_discoverystream/__init__.py", line 52, in _state_publisher
    await discovery.async_state_publish(entity_id, new_state, mybase)
  File "/config/custom_components/mqtt_discoverystream/discovery.py", line 102, in async_state_publish
    await self._async_discovery_publish(entity_id, new_state.attributes, mybase)
  File "/config/custom_components/mqtt_discoverystream/discovery.py", line 127, in _async_discovery_publish
    config = self._build_base(entity_id, attributes, mybase)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mqtt_discoverystream/discovery.py", line 191, in _build_base
    if entry.device_id and name:
```

**Comment by RogerSelwyn** [comment]
Fixed by - https://github.com/RogerSelwyn/mqtt_discoverystream_ha/releases/tag/v0.10.13

**Comment by pergolafabio** [comment]
it is, confirmed

thnx for fast fix! :-)
